Innovate/admin_timeline/urls.py
__all__ = ('urlpatterns',)

from django.conf.urls import patterns, url

urlpatterns = patterns('admin_timeline.views',
    url(r'^$', view='log', name='admin_timeline.log'),
)

Innovate/testproject/urls.py
from django.conf.urls import patterns, include, url
from testproject import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from www import views
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'testproject.views.home', name='home'),
    # url(r'^testproject/', include('testproject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),



    # url(r'', 'www.views.render_main',name='home'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/timeline/', include('admin_timeline.urls')),
    url(r'^admin/', include(admin.site.urls)),

    
    url(r'^upload/', 'www.views.add_album'),
    url(r'^pic/', 'www.views.upload_pic'),
    url(r'^Contact/', 'www.views.view_contact_us'),
    url(r'^picc/', 'www.views.Albumshow'),
    url(r'^cover/', 'www.views.albumpic'),
    url(r'^showpic/', 'www.views.picshow'),
    url(r'^albumcover/', 'www.views.cover'),
    url(r'^aboutus/', 'www.views.aboutuspage'),
    url(r'^deleteAlbum/', 'www.views.renderalbum'),
    url(r'^albumdelete/', 'www.views.delete_album'),
    url(r'^albumshow/', 'www.views.album_pic'),
    url(r'^deletepic/', 'www.views.render_pic'),
    url(r'^deleted/', 'www.views.delete_pic'),
    url(r'^wedding/', 'www.views.albums_gal'),
    url(r'^gallery/', 'www.views.weddinggallery'),
    url(r'^about/', 'www.views.aboutusrendering'),

    url(r'^base/', 'www.views.render_base'),

#     #beshoy renders-front end related urls
    url(r'^sorl/', 'www.views.render_app_test'),
    url(r'^base/', 'www.views.render_base'),
    url(r'^radio/', 'www.views.render_radioAds'),
    url(r'^$', 'www.views.render_main',name='home'),


#     # abdos renders-front end related urls
    url(r'^weddingclips/', 'www.views.show_wedding_videos'),
    url(r'^documentaryclips/', 'www.views.show_documentaries_videos'),
    url(r'^promoclips/', 'www.views.show_promo_videos'),

#     # abdo's functions-bk end related urls
    url(r'^email/', 'www.views.sendemail'),
    url(r'^Delete/Video/(?P<category>\w+)/$', 'www.views.render_videos_to_be_deleted'),
    url(r'^confirmdelete/', 'www.views.delete_video'),
    url(r'^Delete/', 'www.views.render_delete_video_page'),
    url(r'^base/', 'www.views.render_base'),
    url(r'^add/video/', 'www.views.add_video'),
    url(r'^add/contact/', 'www.views.add_contact'),
    url(r'^testincrement/', 'www.views.increment_number_of_views'),
    # url(r'^p/(?P<num>\d+)/$', 'blog.views.page'),
    url(r'^p/(?P<category>\w+)/$', 'www.views.albums_gal'),
    url(r'^t/(?P<category>\w+)/$', 'www.views.landing_page'),
    url(r'^google4b6c7ff943e0c6ed.html', 'www.views.googlecheck'),
    


)
urlpatterns += patterns('django.views.static',
      (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}),
    )

Innovate/www/models.py
from django.db import models
from filer.fields.image import FilerImageField
from django.utils.timezone import utc
import datetime
from datetime import timedelta
from easy_thumbnails.fields import ThumbnailerImageField
from filer.models import *
# Create your models here.


#album table defines elements of the ablum with the title,descr and date of the pictures regarding that album
class Album(models.Model):
	folder=models.ForeignKey(Folder)
	category_choices = (
		('W', 'Wedding'),
		('E', 'Event Making'),
		('A', 'Advertisment'),
		('S', 'Photo Sessions'),
		('ET', 'Event Tools'),
		('AM', 'Ads Making'),
		('EM', 'Event Tools'),
	)
	category = models.CharField(max_length=1, choices=category_choices)
	def __unicode__(self):
	    return str(self.id)+":"+str(self.folder.name)

# #table pics defines the pictures regarding one ablum (no limit)
# class Picture(models.Model):
#     picture1 = FilerImageField()
#     album = models.ForeignKey(Album)
#     # large_thumb = Thumbnailer(upload_to="thumb",blank=True)
#     def __unicode__(self):
#         return str(self.id)


class AblumCover(models.Model):
	album = models.ForeignKey(Album)
	pic=FilerImageField()
	def __unicode__(self):
	    return str(self.album.id)+":"+str(self.album.folder.name)

class About(models.Model):
	maintitle=models.CharField(max_length=50)
	title1=models.CharField(max_length=50)
	description1=models.TextField(max_length='1000')
	picture1 = FilerImageField(related_name='about_pic1')
	title2=models.CharField(max_length=50)
	description2=models.TextField(max_length='1000')
	picture2 = FilerImageField(related_name='about_pic2')
	title3=models.CharField(max_length=50)
	description3=models.TextField(max_length='1000')
	picture3 = FilerImageField(related_name='about_pic3')
	title4=models.CharField(max_length=50)
	description4=models.TextField(max_length='1000')
	picture4 = FilerImageField(related_name='about_pic4')
	def __unicode__(self):
	    return str(self.id)+":"+self.maintitle




class video(models.Model):
	youtube_url = models.CharField(max_length='150')
	video_cover = FilerImageField(related_name='vid_cover')
	title = models.CharField(max_length='150')
	director = models.CharField(max_length='50')
	producer = models.CharField(max_length='50')
	photographer = models.CharField(max_length='50')
	number_of_views = models.IntegerField(default='0')
	video_choices = (
		('W', 'Wedding'),
		('P', 'Promo'),
		('D', 'Documentaries'),
	)
	video_genre = models.CharField(max_length=1, choices=video_choices)
	def __unicode__(self):
	    return str(self.id)+":"+self.title

class contact(models.Model):
	email = models.CharField(max_length='100')
	address_line1 = models.CharField(max_length='100')
	address_line2 = models.CharField(max_length='100')
	address_line3 = models.CharField(max_length='100')
	skype_name = models.CharField(max_length='50')
	telephone_number = models.CharField(max_length='100')
	def __unicode__(self):
	    return str(self.id)+":"+self.email


class main_page(models.Model):
	title=models.CharField(max_length='100')
	slogan=models.CharField(max_length='100')
	is_active=models.BooleanField(default=False)
	def __unicode__(self):
	    return str(self.id)+":"+self.title

class main_page_moviestrip(models.Model):
	main_page = models.ForeignKey(main_page)
	image=FilerImageField()
	title=models.CharField(max_length='100')
	def __unicode__(self):
	    return self.title

class radio_ad(models.Model):
	title=models.CharField(max_length='500')
	url = models.TextField(max_length='1000')
	def __unicode__(self):
	    return self.title
            
class sorl_test(models.Model):
	image=FilerImageField()

Innovate/www/forms.py
from www.models import *
from django import forms


class AlbumForm(forms.Form):
    title= forms.CharField(label="title")
    description = forms.CharField(label='description')
    event_date =  forms.DateField()
 


class PicForm(forms.Form):
	photo = forms.ImageField()
	albumid = forms.CharField(label='albumid',widget = forms.TextInput(attrs={'readonly': 'readonly '}))

class aboutusForm(forms.Form):
	title= forms.CharField(label="title")
	description = forms.CharField(label='description')
	photo = forms.ImageField()


# from django import forms.ValidationError
class VideoForm(forms.Form):
	youtube_url = forms.CharField(max_length='150', required=True)
	title = forms.CharField(max_length='150' ,required=True)
	director = forms.CharField(max_length='50',required=True)
	producer = forms.CharField(max_length='50',required=True)
	photographer = forms.CharField(max_length='50',required=True)
	video_cover = forms.ImageField(required=True)
	video_genre = forms.ChoiceField(widget = forms.Select(), 
					 choices = ([('w','wedding'), ('d','documentary'),('p','promos'), ]),required = True,)

class ContactForm(forms.Form):
	skypename = forms.CharField(max_length='50', required=True)
	telephonenumber = forms.CharField(max_length='50', required=True)
	addressline1 = forms.CharField(max_length='50', required=False)
	addressline2 = forms.CharField(max_length='50', required=False)
	addressline3 = forms.CharField(max_length='50', required=False)
	email = forms.CharField(max_length='50', required=True)


class PicForm(forms.Form):
	photo = forms.ImageField()

Innovate/www/templates/about.html
{% extends "base.html"%}
{% load staticfiles %}
{% load thumbnail %}
{% block header %}
 <script type="text/javascript" src="{% static "js/jquery.min.js" %}" ></script>
 <link href='http://fonts.googleapis.com/css?family=Jura' rel='stylesheet' type='text/css'>
>
    
 <link href="{% static "css/aboutus.css" %}" rel="stylesheet" media="screen">



{% endblock %}
{% block content %}
    
        <style>
            *{
                margin:0;
                padding:0;
            }
            body{
                font-family:Arial;
                background:rgb(68,2,2); ;
            }
            a{
                color:#444;
            }
            a:hover{
                color:#999;
            }
            .title{
                width:500px;
                height:152px;
                position:absolute;
                top:0px;
                left:0px;
                background:transparent url(title.png) no-repeat top left;
            }
            a.back{
                background:transparent url(back.png) no-repeat top left;
                position:fixed;
                width:150px;
                height:27px;
                outline:none;
                bottom:0px;
                left:0px;
            }
            #content{
                margin:0 auto;
            }
            .reference{
                clear:both;
                top:300px;
                left:0px;
                position:absolute;
                text-align:right;
                width:400px;
                padding:20px;
                background-color:#fff;
                -moz-box-shadow:1px 3px 15px #ddd;
                -webkit-box-shadow:1px 3px 15px #ddd;
                box-shadow:1px 3px 15px #ddd;
            }
            .reference p a{
                text-transform:uppercase;
                text-shadow:1px 1px 1px #fff;
                color:#666;
                text-decoration:none;
                font-size:10px;
            }
            .reference p a:hover{
                color:#333;
            }
            .logo{
                margin-top:-15px;
            }
            ul.accordion li.bg1{
                background-image:url(      
                     {% thumbnail about.picture4.file 1000x0 %} 
                        );
            }
            ul.accordion li.bg2{
                background-image:url(
{% thumbnail about.picture3.file 1000x0 %} 
                    );
            }
            ul.accordion li.bg3{
                background-image:url(
{% thumbnail about.picture2.file 1000x0 %} 
                    );
            }
            ul.accordion li.bg4{
                background-image:url(
{% thumbnail about.picture1.file 1000x0 %} 
                    );
            }
        </style>

        <div id="content" >
          
            
             
              <center><h1 
                style="color: #fff;clear: both;
                font-weight: bold;
                font-family: 'Jura', sans-serif;">
                {{about.maintitle}}</h1></center>
<!-- <div id="testclick"><h3>Teeeeeeeeeeeeeest</h3></div> -->

            <div class="container" style="color: #fff;clear: both;
                font-weight: bold;
                font-family: 'Jura', sans-serif;">
                <h1 style="font-weight: bold;
                font-family: 'Jura', sans-serif;">About us:</h1>
                <h3>We are a full oriented and integrated marketing services company where our clients are being provided by complementary combination of creating, planning and handling marketing campaigns including all the required marketing strategies and tools that are  initiated and used in order to reach successfully our client's target market efficiently and effectively. </h3>
            </div>
       </div>
        <!-- The JavaScript -->
     
        <script type="text/javascript">
            $("#testclick").click(function() {
                $('#video-content').hide();
            });    
            $(function() {
                $('#accordion > li').hover(
                    function () {
                        var $this = $(this);
                        $this.stop().animate({'width':'480px'},500);
                        $('.heading',$this).stop(true,true).fadeOut();
                        $('.bgDescription',$this).stop(true,true).slideDown(500);
                        $('.description',$this).stop(true,true).fadeIn();
                    },
                    function () {
                        var $this = $(this);
                        $this.stop().animate({'width':'120px'},1000);
                        $('.heading',$this).stop(true,true).fadeIn();
                        $('.description',$this).stop(true,true).fadeOut(500);
                        $('.bgDescription',$this).stop(true,true).slideUp(700);
                    }
                );
            });
        </script>




{% endblock %}

Innovate/www/templates/add_video.html
{% load staticfiles %}
{% load www_filters%}
<html>
<head>
<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
<link href="{% static "css/add_video.css" %}" rel="stylesheet" media="screen">	
<script type="text/javascript" src="{% static "js/jquery.min.js" %}" ></script>
<script type="text/javascript" src="{% static "js/add_video.js" %}" ></script>

</head>
<body>
<div>
<div style="margin-top:15px;">
		{% if success %}
		<div id="success_alert" style="margin-left: 25px;background-color:green; opacity:0.6;text-align:center;margin-bottom: 20px;height:123px;"><h2>Your video has been added successfully</h2></div>
	{% endif %}
	<h2 >Please enter the video details that you want to add.</h2>

	<form class="form-horizontal" enctype="multipart/form-data" method="post" action="/add/video/">
	{% csrf_token %}
 	 	<div class="form-group" >
			<label class="col-lg-2 control-label" for="id_youtube_url">Youtube url:</label> 
			<div class="col-lg-10">
				<input placeholder="required" class="form-control" id="id_youtube_url" maxlength="150" name="youtube_url" type="text" />
			</div>
		</div>
		<div id='video_tag' style="margin-left: 130px;"></div>
		
		<div class="form-group" >
			<label class="col-lg-2 control-label" for="id_title">Title:</label> 
			<div class="col-lg-10">
				<input placeholder="required" class="form-control" id="id_title" maxlength="150" name="title" type="text" /><label id="title_error" style="display:none">Invalid</label>
			</div>
		</div>
		
		
		<div class="form-group">
			<label class="col-lg-2 control-label" for="id_director">Director:</label>
			<div class="col-lg-10">
			<input placeholder="required" class="form-control" id="id_director" maxlength="50" name="director" type="text" /><label id="title_director" style="display:none">Invalid</label>
			</div>
		</div>
		
		
		<div class="form-group">
			<label class="col-lg-2 control-label" for="id_producer">Producer:</label>
			<div class="col-lg-10">
				<input  placeholder="required" class="form-control" id="id_producer" maxlength="50" name="producer" type="text" /><label id="producer_error" style="display:none">Invalid</label>
			</div>
		</div>
		

		<div class="form-group">
			<label class="col-lg-2 control-label" for="id_photographer">Photographer:</label>
			<div class="col-lg-10">
				<input  placeholder="required" class="form-control" id="id_photographer" maxlength="50" name="photographer" type="text" /><label id="photographer_error" style="display:none">Invalid</label>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2 control-label" for="id_video_cover">Video Image:</label>
			<div class="col-lg-10">
				<input id="id_video_cover" maxlength="50" name="video_cover" type="file" />
			</div>
		</div>
		
		
		<div class="form-group">
			<label class="col-lg-2 control-label" for="id_video_genre">Video genre:</label>
			<select id="id_video_genre" name="video_genre">
				<option value='w'>Wedding</option>
				<option value='p'>Promos</option>
				<option value='d'>Documentaries</option>
			</select>	
		</div> 
		

		<input style="margin-left:597px;" class="btn btn-default" type="submit" value="Submit" />
	</form>
</div>

</div>


</body>
</html>
<div>
	

Innovate/www/templates/albumshow.html
{% load staticfiles %}

<html>
<head>
  <script type="text/javascript" src="{% static "js/jquery-1.9.1.min.js" %}" ></script>
  <script type="text/javascript" src="{% static "js/jquery.min.js" %}" ></script>
</head>
<body>


    <div class = "selectAlbum">
		   
				 <select id = "selectalbum">
				 	 <option> ALBUMS</option>
				    {% for a in album %}
                <option value="{{a.id}}">{{a.title}}</option>
					         {% endfor %}
				 </select> 
			 
    </div>
<script>
$('#selectalbum').change(function(){
	window.location.replace("/deletepic/?albumid="+$(this).val())
});

// function setalbumcover(selectpic){
// window.location.replace("/albumcover/?picture="+selectpic)

// };
</script>
</body>
</html>

Innovate/www/templates/base.html
<html>
  <head>
    {% load staticfiles %}
    <link rel="shortcut icon" href="{% static "images/letter_i_red.ico" %}">
    <link href="{% static "css/mainpage.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "css/menu.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
    <script type="text/javascript" src="{% static "js/jquery-1.9.1.min.js" %}" >
    </script>
    <link href='http://fonts.googleapis.com/css?family=Jura' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
    a {
      text-decoration: none;
      }
      .navbar-inverse .navbar-nav>li>a {
      color: #FFF;
      }
      .navbar-inverse .navbar-nav>li>a:hover, .navbar-inverse .navbar-nav>li>a:focus {
      color: #999;
      background-color: transparent;
      }
      .dropdown-menu>li>a:hover, .dropdown-menu>li>a:focus {
      color: #fff;
      text-decoration: none;
      background-color: rgba(129, 13, 13, 0.84);
      font-weight: 600;
      }
      .dropdown-menu>li>a {
      display: block;
      padding: 3px 20px;
      clear: both;
      font-weight: 400;
      line-height: 1.428571429;
      color: #333;
      white-space: nowrap;
      font-size: 17;
      }
      </style>
    
    {% block header %}
    {% endblock %}
    <title>
      {{title}}
    </title>
  </head>
  <body  id="radial-center">
    <div class="container-fluid">
      

          
          
          <div  id="menu_box" style="margin-left: 0px" >
            <img>
            <a href="/" style="position: relative;left: 0px;float: left;white-space: nowrap;height:50px;top: -6px;z-index: 999" title="CLick here to go to Home">
                
              </a>
          
            {% include "nav.html" %}
        </div>
      </div>
          </div>
          
          
          
          <center>
            
          
          <br>
          {% block content_div %}
          <div id="main_div" class="row " style="display:none;position: relative;z-index: 2;margin-top: 20px">
          {% endblock %}

            {% block content %}
            
            {% endblock %}
          </div>
          <br>
          
          
          
          
         <!-- <footer id = "footer">
            <p style = "text-align: center;
width: 99%;
position: fixed;
color: white;
bottom: 0px;
font-size: 15px;
z-index: 9999;
background-color: rgba(48, 23, 23, 0.2);
-webkit-margin-before: 0;
-webkit-margin-after: 0;" >
  <a href="http://www.facebook.com/InnovateWD">
    <img src="{% static 'images/icons/facebook.png'%}" style="width:32px;"  alt="FB" target="_blank">
  </a>
  <a href="http://instagram.com/Innovate_m_p" target="_blank">
    <img src="{% static 'images/icons/Instagram-32-4.png'%}" style="width:32px;" alt="FB">
  </a>
  <a href="">
    <img src="{% static 'images/icons/Soundcloud-orange-32.png'%}" style="width:32px;" alt="FB"  target="_blank">
  </a>
  <a href="http://www.youtube.com/user/013Pete">
    <img src="{% static 'images/icons/youtube.png'%}" style="width:32px;" alt="FB"  target="_blank">
  </a>
  <a href="https://twitter.com/InnovateMP">
    <img src="{% static 'images/icons/twitter.png'%}" style="width:32px;" alt="FB"  target="_blank">
  </a>
  <a href="">
    <img src="{% static 'images/icons/google.png'%}" style="width:32px;" alt="FB"  target="_blank">
  </a>
  <a href="">
    <img src="{% static 'images/icons/pinterest.png'%}" style="width:32px;" alt="FB"  target="_blank">
  </a>
  
              </p>
          </footer> -->
          </center>

          <script type="text/javascript" src="{% static "js/jquery.easing.1.3.js" %}" >
          </script>
          <script  type="text/javascript">
            
            
            
            
            
            
          $(function() {
              var $loader = $('#st_loading');
              //Show a Loading untill the main div is all loaded
              $('#main_div').ready(function() {
                  $loader.hide();
                  $('#main_div').fadeIn(3000);
              });
              var $menu = $('#sdt_menu');
              var $menu_box = $('#menu_box');
              $menu_box.bind('mouseenter', function() {
                  $menu.stop().animate({
                      'top': '70px'
                  }, 400, 'easeOutBack');
              });
              $menu_box.stop().bind('mouseleave', function() {
                  $menu.animate({
                      'top': '0px'
                  }, 400, 'easeOutBack');
              });
              $('#sdt_menu > li').bind('mouseenter', function() {
                  var $elem = $(this);
                  $elem.find('img').stop(true).animate({
                      'width': '160px',
                      'height': '150px',
                      'left': '0px'
                  }, 400, 'easeOutBack').andSelf().find('.sdt_wrap').stop(true).animate({
                      'z-index': '16',
                      'top': '120px'
                  }, 500, 'easeOutBack').andSelf().find('.sdt_active').stop(true).animate({
                      'z-index': '16',
                      'height': '150px'
                  }, 300, function() {
                      var $sub_menu = $elem.find('.sdt_box');
                      if ($sub_menu.length) {
                          var left = '160px';
                          if ($elem.parent().children().length == $elem.index() + 1) left = '-160px';
                          $sub_menu.show().animate({
                              'left': left
                          }, 200);
                      }
                  });
              }).bind('mouseleave', function() {
                  var $elem = $(this);
                  var $sub_menu = $elem.find('.sdt_box');
                  if ($sub_menu.length) $sub_menu.hide().css('left', '0px');
                  $elem.find('.sdt_active').stop(true).animate({
                      'height': '0px'
                  }, 300).andSelf().find('img').stop(true).animate({
                      'width': '0px',
                      'height': '0px',
                      'left': '85px'
                  }, 400).andSelf().find('.sdt_wrap').stop(true).animate({
                      'top': '15px'
                  }, 500);
              });
          });
          
          </script>
          {% block endjs %}
          {% endblock %}
      </div>
      <script src="{% static "js/bootstrap.min.js" %}"></script>
      <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44215885-2', 'innovateegypt.com');
  ga('send', 'pageview');

</script>
  </body>
</html>

Innovate/www/templates/cover.html
{% load staticfiles %}

<html>
<head>
  <script type="text/javascript" src="{% static "js/jquery-1.9.1.min.js" %}" ></script>
  <script type="text/javascript" src="{% static "js/jquery.min.js" %}" ></script>
</head>
<body>

 {% if selected_value %} 
<p>You picked {{selected_value}}.</p> 
{% else %} 
<p>Choose the value you want and click <em>Submit</em>.</p> 
{% endif %}      
    <div class = "selectAlbum">
				 <select id = "albumselect"name = "answer">
				 	 <option > ALBUMS</option>
				    {% for a in album %}
                <option value="{{a.id}}" >{{a.title}}</option>
					         {% endfor %}
				 </select> 
				  <input type="submit" value="Submit">

				
		      
    </div>
    </form> 
     
<div id = "selectpic">
              {% for p in pic %}
             <img  onClick='setalbumcover({{p.id}})' src = '{{p.picture1.url}}'></img>
          
                 {% endfor %}
</div>
 <script>
$('#albumselect').change(function(){
	window.location.replace("/showpic/?albumid="+$(this).val())
});

function setalbumcover(selectpic){
window.location.replace("/albumcover/?picture="+selectpic)

};
</script>
             
</body>
</html>

Innovate/www/templates/deleteAlbum.html
{% load staticfiles %}

<html>
<head>
  <script type="text/javascript" src="{% static "js/jquery-1.9.1.min.js" %}" ></script>
  <script type="text/javascript" src="{% static "js/jquery.min.js" %}" ></script>
</head>
<body>


    <div class = "selectAlbum">

			<p> click on the ablum you wish to delete </p>
               {% for a in album %}
    <label onClick='delete1("{{a.id}}");'>{{a.title}}</label> 
                {% endfor %}                 
        

	</div>

<script>
function delete1(id)
  {
    $.ajax({
    url: '/albumdelete/',
    type: 'POST',
    data: {
      "albumid":id ,
    },
    success: function(result){
      alert("album has been hidden sucessfully");

    },
  });
}
</script>



</body>
</html>

Innovate/www/templates/gallery2.html
{% extends "base.html"%}
{% load staticfiles %}
{% block header %}
 <script type="text/javascript" src="{% static "js/jquery.min.js" %}" ></script>
 <script type="text/javascript" src="{% static "js/jquery-1.10.2.min.js" %}" ></script>
 <script type="text/javascript" src="{% static "js/lightbox-2.6.min.js" %}" ></script>
 <script type="text/javascript" src="{% static "js/modernizr.custom.js" %}" ></script>

 <link href='http://fonts.googleapis.com/css?family=Jura' rel='stylesheet' type='text/css'>
 <link href="{% static "css/lightbox.css" %}" rel="stylesheet" media="screen">
 <link href="{% static "css/screen.css" %}" rel="stylesheet" media="screen">
 <link href="{% static "css/wedding_pics.css" %}" rel="stylesheet" media="screen">




{% endblock %}
{% block content %}

<div class = "title" >
<p> Wedding Pictures</p> </div>
	<div class="weddingppics">
   {% for p in picture %}

	  
		<a href="{{p.picture1.url}}" data-lightbox= "pics">
     
		<img src='{{p.picture1.url}}'width = "800" height="400"  alt="blah" >
			</a> 

		{% endfor %}




</div>





{% endblock %}

Innovate/www/templates/google4b6c7ff943e0c6ed.html
google-site-verification: google4b6c7ff943e0c6ed.html

Innovate/www/templates/upload.html
{% load staticfiles %}
<html>
<head>
	<title></title>
</head>

<body>
	<div class "AlbumForm">
		<p> Add Album: </p>
		<form action="" method="post">
	        <div class = "errors">
	        
				{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
			</div>
			<div class="album">
				<label > Title </label>
		        {% if form.title.errors %}<p class="error">{{ form.title.errors }}</p>{% endif %}
		       
		        <p>{{ form.title }}</p>
			</div>
			<div class="album">
				<label > description </label>
		        {% if form.description.errors %}<p class="error">{{ form.description.errors }}</p>{% endif %}
		       
		        <p>{{ form.description }}</p>
			</div>
			<div class="album">
				<label > event date</label>
		        {% if form.event_date.errors %}<p class="error">{{ form.event_date.errors }}</p>{% endif %}
		       
		        <p>{{ form.event_date }}</p>
			</div>
			<div class = "submit">
			 <input type="submit" value="Submit">
			</div>
        </div>
		</form>
	</div>

		    
		
		

</body>
</html>